ASPNET_MVC_Web/ASPNET_MVC_Web/Models/List.cs
using System;
using System.Collections.Generic;

namespace ASPNET_MVC_Web.Models
{
   public enum eListType
   {
      Standard = 0,
      WithBeta = 1,
      WithDebugSymbols = 1,
      PAKFiles = 2,
      PAKFilesWithBeta = 3,
   }

   public class ListViewModel
   {
      public List<clsBinary> BinaryList { get; set; }
      public string Message { get; set; }
      public eListType ListType { get; set; }

      public ListViewModel ()
      {
         this.Clear();
      }

      private void Clear ()
      {
         BinaryList = new List<clsBinary>();
         Message = string.Empty;
         ListType = eListType.Standard;
      }
   }

   public class clsBinary
   {
      public Guid id { get; set; }
      public string fileName { get; set; }
      public string fileNamePDB { get; set; }
      public string date { get; set; }
      public string arch { get; set; }
      public string changes { get; set; }
      public bool beta { get; set; }

      public clsBinary ()
      {
         this.Clear();
      }

      private void Clear ()
      {
         id = new Guid();
         fileName = string.Empty;
         fileNamePDB = string.Empty;
         date = string.Empty;
         arch = string.Empty;
         changes = string.Empty;
         beta = false;
      }
   }
}

ASPNET_MVC_Web/ASPNET_MVC_Web/Controllers/DownloadController.cs
using ASPNET_MVC_Web.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ASPNET_MVC_Web.Controllers
{
    public class DownloadController : BaseController
    {
        static readonly string APIVERSION = "1";

        [HttpPost]
        public FileResult _GetAPIVersion()
        {
            string fileName = "version.txt";

            return File(Encoding.UTF8.GetBytes(APIVERSION), "text/plain", fileName);
        }

        [HttpPost]
        public FileResult _GetMD5(int? type, int? arch, int? beta, int? pak)
        {
            int _beta = 0;
            string fileName = "error.txt";
            StringBuilder Query = new StringBuilder(4096);
            Collection<SqlParameter> Parameters = new Collection<SqlParameter>();

            if (type == null)
            {
                WriteLog("GetMD5(): Bad request from {0}.  type is null.", Request.UserHostAddress);
                goto errorFile;
            }

            if ((type == BUILD) && (arch == null))
            {
                WriteLog("GetMD5(): Bad request from {0}.  arch is null for BUILD query.", Request.UserHostAddress);
                goto errorFile;
            }

            if ((type == PAK) && (pak == null))
            {
                WriteLog("GetMD5(): Bad request from {0}.  pak is null for PAK query.", Request.UserHostAddress);
                goto errorFile;
            }

            if ((beta != null) && (beta > 0))
            {
                _beta = 1;
            }

            switch (type)
            {
                case BUILD:
                    Query.AppendLine("SELECT [O].[md5] FROM [Daikatana].[dbo].tblBuildsBinary AS O");

                    switch (arch)
                    {
                        case ARCHWIN32:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[arch]='Win32')");
                            fileName = "dk_win32.md5";
                            break;
                        case ARCHWIN64:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[arch]='Win64')");
                            fileName = "dk_win64.md5";
                            break;
                        case ARCHLINUX32:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[arch]='Linux')");
                            fileName = "dk_linux.md5";
                            break;
                        case ARCHLINUX64:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[arch]='Linux_x64')");
                            fileName = "dk_linux_x64.md5";
                            break;
                        case ARCHFREEBSD:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[arch]='FreeBSD')");
                            fileName = "dk_freebsd_x64.md5";
                            break;
                        case ARCHOSX:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[arch]='OSX')");
                            fileName = "dk_osx.md5";
                            break;
                        case ARCHDOS:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[arch]='DOS')");
                            fileName = "dk_dos.md5";
                            break;
                        default:
                            goto errorFile;
                    }
                    Parameters.Add(clsSQL.BuildSqlParameter("@beta", System.Data.SqlDbType.Bit, _beta));
                    break;
                case PAK:
                    Query.AppendLine("SELECT [O].[md5] FROM [Daikatana].[dbo].[tblPAKsBinary] AS O");
                    switch (pak)
                    {
                        case PAK4:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblPAKsLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[type]='pak4.pak')");
                            fileName = "pak4.md5";
                            break;
                        case PAK5:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblPAKsLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[type]='pak5.pak')");
                            fileName = "pak5.md5";
                            break;
                        case PAK6:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblPAKsLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[type]='pak6.pak')");
                            fileName = "pak6.md5";
                            break;
                        default:
                            goto errorFile;
                    }
                    Parameters.Add(clsSQL.BuildSqlParameter("@beta", System.Data.SqlDbType.Bit, _beta));
                    break;
                default:
                    goto errorFile;
            }

            try
            {
                using (clsSQL dbSQL = new clsSQL(SQLConnStr))
                {
                    if (dbSQL.Query(Query.ToString(), Parameters.ToArray()) == false)
                    {
                        WriteLog("GetMD5(): Bad request from {0}.  Query failed.  Reason: {1}\n", Request.UserHostAddress, dbSQL.LastErrorMessage);
                        goto errorFile;
                    }

                    if (dbSQL.Read())
                    {
                        return File(Encoding.UTF8.GetBytes(dbSQL.ReadString(0)), "text/plain", fileName);
                    }
                }
            }
            catch (Exception ex)
            {
                WriteLog("GetMD5(): Bad request from {0}.  Query failed.  Reason: {1}\n", Request.UserHostAddress, ex.Message);
            }

        errorFile:
            Response.StatusCode = 404;
            Response.TrySkipIisCustomErrors = true;
            throw new HttpException(404, "Not found");
        }

        [HttpPost]
        public FileResult _GetFileName(int? type, int? arch, int? beta, int? pak)
        {
            int _beta = 0;
            string fileName = "error.txt";
            StringBuilder Query = new StringBuilder(4096);
            Collection<SqlParameter> Parameters = new Collection<SqlParameter>();

            if (type == null)
            {
                WriteLog("GetFileName(): Bad request from {0}.  type is null.", Request.UserHostAddress);
                goto errorFile;
            }

            if ((type == BUILD) && (arch == null))
            {
                WriteLog("GetFileName(): Bad request from {0}.  build is null for BUILD query.", Request.UserHostAddress);
                goto errorFile;
            }

            if ((type == PAK) && (pak == null))
            {
                WriteLog("GetFileName(): Bad request from {0}.  pak is null for PAK query.", Request.UserHostAddress);
                goto errorFile;
            }

            if ((beta != null) && (beta > 0))
            {
                _beta = 1;
            }

            switch (type)
            {
                case BUILD:
                    Query.AppendLine("SELECT [O].[filename] FROM [Daikatana].[dbo].[tblBuilds] AS O");

                    switch (arch)
                    {
                        case ARCHWIN32:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[arch]='Win32')");
                            fileName = "dk_win32.txt";
                            break;
                        case ARCHWIN64:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[arch]='Win64')");
                            fileName = "dk_win64.txt";
                            break;
                        case ARCHLINUX32:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[arch]='Linux')");
                            fileName = "dk_linux.txt";
                            break;
                        case ARCHLINUX64:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[arch]='Linux_x64')");
                            fileName = "dk_linux_x64.txt";
                            break;
                        case ARCHFREEBSD:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[arch]='FreeBSD')");
                            fileName = "dk_freebsd_x64.txt";
                            break;
                        case ARCHOSX:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[arch]='OSX')");
                            fileName = "dk_osx.txt";
                            break;
                        case ARCHDOS:
                            Query.AppendLine("INNER JOIN [Daikatana].[dbo].[tblLatest] I ON ([I].[id]=[O].[id] AND [I].[beta]=@beta AND [I].[arch]='DOS')");
                            fileName = "dk_dos.txt";
                            break;
                        default:
                            goto errorFile;
                    }

ASPNET_MVC_Web/ASPNET_MVC_Web/Views/List/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Daikatana Updater SQL Query</title>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    @model ASPNET_MVC_Web.Models.ListViewModel
    @using ASPNET_MVC_Web.Models
    @{
        ViewBag.Title = "Daikatana Updater SQL Query";
        Layout = null;
    }
    @if (!String.IsNullOrEmpty(Model.Message))
    {
        <p><b>@Model.Message</b></p>
    }
    else
    {
        <div>
            <table border="1">
                <thead>
                    <tr>
                        @if (Model.ListType == eListType.PAKFiles || Model.ListType == eListType.PAKFilesWithBeta)
                        {
                            <th>Type</th>
                        }
                        else
                        {
                            <th>Architecture</th>
                        }
                        <th>Date</th>
                        @if (Model.ListType == eListType.WithBeta || Model.ListType == eListType.PAKFilesWithBeta)
                        {
                            <th>Beta</th>
                        }
                        <th>File</th>
                        @if (Model.ListType != eListType.PAKFiles && Model.ListType != eListType.PAKFilesWithBeta)
                        {
                            <th>Debug Symbol</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (clsBinary listElement in Model.BinaryList)
                    {
                        <tr>
                            <td>@listElement.arch</td>
                            <td>@listElement.date</td>
                            @if (Model.ListType == eListType.WithBeta || Model.ListType == eListType.PAKFilesWithBeta)
                            {
                               <td>
                               @if (listElement.beta == true)
                               {
                                   <center><b>X</b></center>
                               }
                               </td>
                            }
                               <td>
                                   @if (Model.ListType == eListType.PAKFiles || Model.ListType == eListType.PAKFilesWithBeta)
                                   {
                                       @Html.ActionLink(listElement.fileName, "Index", "Download", new { _id = listElement.id.ToString(), Type = 2 }, null)
                                   }
                                   else
                                   {
                                       @Html.ActionLink(listElement.fileName, "Index", "Download", new { _id = listElement.id.ToString(), Type = 0 }, null)
                                   }
                               </td>
                            @if (Model.ListType != eListType.PAKFiles && Model.ListType != eListType.PAKFilesWithBeta)
                            {
                                <td>
                                    @if (String.IsNullOrWhiteSpace(listElement.fileNamePDB) == false)
                                    {
                                       @Html.ActionLink(listElement.fileNamePDB, "Index", "Download", new { _id = listElement.id.ToString(), Type = 1 }, null)
                                    }
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    </body>
</html>